apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: frontend
          command:
            - ng
            - serve
            - --host
            - 0.0.0.0
            - --public-host
            - "bolnica-1.k8s.elab.rs"
            - --port
            - "4200"
          ports:
            - containerPort: 4200
